sudo: false
language: ruby
cache: bundler
rvm:
- 2.5.1
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
  - secure: y6YxnjX13Ob/DxS9SXmiMAjmIXnvsCGAVWrmOy2TuwvfcFv18sb94efO8q10F4uqME6D5/OegTr0w0fXcN9eJA+0f2hWWoSV9j/+4ocKdoAxdKAEpuGn2P2NVz3c2R+4o8fscM+d26KDBpC+eXIbzPF5rAC34YUmQLYp2QOh9mc8PPi/W5ePEAl2qxYNFmMkaFIXGVUMvLSXL23RKDWlnB5bCsf7qYRDbCd4lsS62gNdwpg2nFV3cK1ExaFjF+hZSstPCUH65izX8Ti3qdYYNmnzM4UttT+gyS0UhMqDCMpWkK40p0b6u3q1IRn+M4ohBncOlZYZ3QwwdVojDPf8GuAsg6UZByrdJibITY5rKAoGl6sMzNjPAca9FzPxB1r3sHKy/3FcbsO/DnNHrX8cVJN+S44oUcZCO9p3S+WAXXQFgGJfI7/HM5wisSTpVKiSO1gLl4EGLOGIYOTW63/fXcXb4zBIr0S7Q0ZInTbmD6ZVBug/wq80GPzb1KcwNHalJj+H0rcswB9HH2RtcOAGlHdeigFJBnDd5F9pVsa2ngZJtGCxmiZt4DXx/e2D00YhpWO+na+kXwl9oGiM2iyG9zOpANpih6rZVaYvVJO2Zr0p2a7BnkdurOmtgCRgkW7ySn21WOw6Ue0Fm9Wg/YG86S6ziD/vRqBCvVp/L7zfVPc=
branches:
  only:
  - main
