sudo: false
language: ruby
cache: bundler
rvm:
- 2.5.1
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  - secure: AVAYhTiEhxb6ic0G9FrhtfG8zkQSCG183PDurE8Mnlnq58ryz1ucxO0N38K/xbff3lExOLVPFb++O5tmBMLpfspySv9dZEIv1rpxuNUYsqqKphwjMyP2eIi/w8qFO/W6lTxGx7SQMupqMp4er5mjYjcB4686T1X3Hmdi10v1FQnOtDNac9KL3sMMLrMZorRPmC0DWZsq2ScIdMFUKUM2SLahHvklEgLNoqw2TCW6o8D8ytk4AP+NOP/nm18WwNqn6E7WxQf6h0oe2AlqS4bsOrVYPSm7R83mgq1NVkcf6l8JDj2tEIw0VOdcSDLw94o7DCjQlfE8GuujJtX5nbDOuKDgh3UUQWqM0ZM82yssVfodGqKSn9wrJIP29HttoUP5GG5AgLjfuZfi68o8M1J0atD4Do103up9G1Ye4S15XvjkL4k0xJw0dD9AzRdEX7w/TwP9maAYUrmgfxM7bQVtGRkpodLRmmJ/ictLAADm6XsETotPN0/23luLPNqe9uzZymA+OlB/ZJCH/DQK38ifrMTfT5ZYc+tc7yQg4IbCLd8uuG3ejI436O75kJ+H5gzdnUjbbPuguskYNbUKOXvUTmXQbz4OJv61ayR5m1gBrBiECcTGDkS661+1QwQtRAECakXpONXN5QdZeKpGONxuUQMu+DfqeXAbjPPAxKIkLxU=
branches:
  only:
  - main
