sudo: false
language: ruby
cache: bundler
rvm:
- 2.5.1
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
  - secure: qXzd/AcjNiM6zwVWr36JFL8xhCnRc8Y9zJs2/t13AmvPm3e11RRMFhoVDRvTN5VNQeZbrLxs3goWkQjSVn9GmOCCdV+a3wQ2T7CPeXBOrDf7SDd7AGsMyvaci3nHgAdH/z8LpQP+pglLtDilHWwDrwzy2jBGlXek4qqA70diCWw1/OJBPY1d8m1tpWtiozl1cFJsfYVAdqkiLJyBV52u+T+jboODor+iT7TeyoV6JpBUrIHXr/MfHVuhs2wnnt3UfCaEzG1mw9x10IXbFIzwlMrd0BJBzEVpBDb6SH/IqJB3xBtJEiT4zMDnMbK2zYfTZiwJL6349n/yG8INQIFIWU6fxlV9kohB7b3N9wr8dVPU3ooQf9yyXnJpjH23tuaXtmF6xOP5aB9tubkbn57kV0Nf9gJKr8+xq3qN52SzKrwz89FCtmToTjfMOQrmxF0e+dWP/MvSx6cQn/dT6hKMvJtO8ufAYpgwP1SrozJQgwQSWJSCH/S/wwaeQ1yA4ZVml5QMXk7z+A32HvXhLw/gYIYOfZMNGhcB13MmnmQ48OxwVUzHl/TocIR2qs/vh8dbkZLOgGZfhoqZWxCW91OJUGDXTSSK+8LfNpNXtrUeEjJfFk1/7RmaQQNM4RDDDRr2Btj1zDnCROGIorn3R8A20gBK2OBA+dBPcP/BFuUa7QM=
branches:
  only:
  - main
