sudo: false
language: ruby
cache: bundler
rvm:
- 2.5.1
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
  - secure: QNp4byYBYWhwZqAtPZuLS0JGxI+lgpLTjyLGjmRgphzxcKTF50acvhUtQ3e15/FHElKjGCAaiUd2s4+cWsIjhUTSIOImNi0emGQgYibrsrpjRxHHg4CVWHBNW1AEiXAWTC7lsvuiO2OJCyo5jeRpKNnuGR7Tdvy8RRHlok1Azf4LCA/0q48PXQJganGArV0pd4vJv5R+dYMxDHmDhFq6c/1yb/EcHlHcZeVFJWjkuQ/CON4Svkt79A94gg9LZRneizRxpd24+DGuX2ecnmSb1Iq+fQsqE8T7iOm5LBdx3E6vbg7PvB4Kcey+y2OD3l8oOcHUneQAPR7HylPj2gLHAWz5j4yWWUiLB3jR7HfzLQnSc0YNv1HJOR4fyTx+ZN5FtIM6yZFTkDl65zL7k/1i5qWkT3Hb1YbFkbFF0aLnQi5tvCClUW1uX8uymWi1zJP2ysVbsLwao5/S3R6/6Lajk/gwIaNcMVXLhqVYVQk0HJEACLPzSkqIso/fCcSc8PC9MrfPJBYFkfe5m27abu2OwhYhyL2rZzg8uqxhfaROHsUmDi8c/Cmlg8mWxLBndrvXO93FcZ6r1KXUHNVVQGILgKJN5Eccmikvk7HsLhzgQh7qryYQDsx/X7d5vpHKBsIu82rBVwA+YFPLlO3WLs7rAl7nD2u1GOBgdNkT+jguniQ=
branches:
  only:
  - main
