sudo: false
language: ruby
cache: bundler
rvm:
- 2.5.1
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
  - secure: R0TJCeHtCAh1DwEgdT3CGzR7f6qjil7Gz6p1b9YYTQCZ8ES79pNapOZ+g3RSSYqp6kwSGodtudT6siozgVuF4OEI5Bc9UGdvJiOMdvYF00lUZxA02FFKKScLinTvi+1AqHPYzLEtYZVOaZW54gEvOAjkBEaNwZkDf8ahIYUYtWLfpWeF8zeOXfH0gvs2ZIYBTBoLCJ9C/8/ycjj2FsKOHyq9PvlTAgGLz5wuYLECcuumDWUe+1JYVR3OqKxjB5qqDSjXWOX5H38pkqrM6WLTx8c7+RsNeKIThGTSUJDLwsLjbKV4t71dbFqyEdpdNza5toFYapXhkdPridkZ0o/yS3OAJfBqvFH0xoul9SS4AHLZJdn4BGO217ZRXBlYi7i1YtkWQRWTG//LHbLK2kwtgE04QOOu7ddd9Ac+9ZaZkIjyS2qEk3XmMl5yBLFhiRQ5ICedeHWzTgHLLOIR4zjUoxD3bCLDHgpeLpRkxn8K2N2ho2bf2rb6BqhiMa89N+0wCiV6BgGypsTIuHB5XgOljB/04nDkhiaXmSL2yI5iaLME1Yoz752D1S6K5jw3HUzBXjYsTOSQxdROdooasMMleOkgsqz3OqkCI+1bdVG/VRTxQjse3B5d9OlpUe8bJcP2F+sjYZJsZvz1CUcqh7y66MzLQ679plkN1O8m1AdMHHY=
branches:
  only:
  - main
